baseURL       = "https://stroem.lydbydissing.com/"
languageCode  = "en-us"
title         = "STRØM 1.0 | Fully Open Source WiFi and Bluetooth Speaker"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "STRØM"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
#  [[menu.nav]]
#    name    = "Get in touch"
#    url     = "contact"
#    weight  = 3

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "STRØM 1.0 | Fully Open Source WiFi and Bluetooth Speaker"
  author = "Lyd by Dissing"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  #fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_full_name         = "Full Name"
    #placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    #placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "Ask about the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"


  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/stroem-1_0-dark_background.webp"
    heading               = "The STRØM 1.0 Wifi Streaming Speaker Project"
    tagline               = "FULLY OPEN SOURCE SPEAKER DESIGN"
    primary_button        = "Learn more about the project"
    primary_button_url    = "portfolio"
    secondary_button      = "Join the BETA program"
    secondary_button_url  = "blog/join-the-beta"

  [params.portfolio]
    enable    = true
    title     = "MORE FROM THE PROJECT"
    subtitle  = "The Strøm open source speaker project have been started with the main goal of creating a fully functional “streaming speaker”, but as an open sourced product. One that you can choose to buy fully built and tested, or choose to built it yourself."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cabinet-layer-2-drawing-crop.png"
    title               = "JOIN THE PROJECT"
    primary_button      = "Join the Beta"
    primary_button_url  = "contact"
    secondary_button    = "Tell me more"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Lyd by Dissing ApS, Aabjergvej 12M, 2720 Vanloese"
      phone   = "+45 20 68 33 02"
      email   = "contact@lydbydissing.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "https://www.linkedin.com/company/lyd-by-dissing-aps/"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://facebook.com/lydbydissing/"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/lydbydissing/"
